//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers
    {
        public AspNetUsers()
        {
            this.Empresa = new HashSet<Empresa>();
            this.EncuestaPerfilesPetroleo = new HashSet<EncuestaPerfilesPetroleo>();
            this.PersonasReunionesPerfiles = new HashSet<PersonasReunionesPerfiles>();
        }
    
        public string Id { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public int EmpresaId { get; set; }
        public bool Activo { get; set; }
        public bool PasswordChange { get; set; }
    
        public virtual ICollection<Empresa> Empresa { get; set; }
        public virtual ICollection<EncuestaPerfilesPetroleo> EncuestaPerfilesPetroleo { get; set; }
        public virtual ICollection<PersonasReunionesPerfiles> PersonasReunionesPerfiles { get; set; }
    }
}
