//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargos
    {
        public Cargos()
        {
            this.EncuestaPerfilesPetroleo = new HashSet<EncuestaPerfilesPetroleo>();
        }
    
        public int id { get; set; }
        public string Cargo { get; set; }
        public int EspecialidadId { get; set; }
    
        public virtual OtraEspecialidad OtraEspecialidad { get; set; }
        public virtual ICollection<EncuestaPerfilesPetroleo> EncuestaPerfilesPetroleo { get; set; }
    }
}
