//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.CulminacionFinal = new HashSet<CulminacionFinal>();
            this.EmpresaEspecialidad = new HashSet<EmpresaEspecialidad>();
            this.PersonaDiligencia = new HashSet<PersonaDiligencia>();
            this.JefeGesHum = new HashSet<JefeGesHum>();
            this.EncuestaPerfilesPetroleo = new HashSet<EncuestaPerfilesPetroleo>();
            this.PersonasReunionesPerfiles = new HashSet<PersonasReunionesPerfiles>();
        }
    
        public int Id { get; set; }
        public string Empresa1 { get; set; }
        public int NoTotalTrabajadores { get; set; }
        public string Nit { get; set; }
        public string UserID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<CulminacionFinal> CulminacionFinal { get; set; }
        public virtual ICollection<EmpresaEspecialidad> EmpresaEspecialidad { get; set; }
        public virtual ICollection<PersonaDiligencia> PersonaDiligencia { get; set; }
        public virtual ICollection<JefeGesHum> JefeGesHum { get; set; }
        public virtual ICollection<EncuestaPerfilesPetroleo> EncuestaPerfilesPetroleo { get; set; }
        public virtual ICollection<PersonasReunionesPerfiles> PersonasReunionesPerfiles { get; set; }
    }
}
