//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaEspecialidad
    {
        public int Id { get; set; }
        public int EmpresaId { get; set; }
        public int Especialidadid { get; set; }
        public Nullable<bool> EspecialidadCulminada { get; set; }
        public Nullable<bool> NoAplica { get; set; }
        public Nullable<System.DateTime> FechaCulminacion { get; set; }
        public string UserId { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual OtraEspecialidad OtraEspecialidad { get; set; }
    }
}
