//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EncuestaPetroleoEntities : DbContext
    {
        public EncuestaPetroleoEntities()
            : base("name=EncuestaPetroleoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TipoCago> TipoCago { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Cargos> Cargos { get; set; }
        public virtual DbSet<CulminacionFinal> CulminacionFinal { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<EmpresaEspecialidad> EmpresaEspecialidad { get; set; }
        public virtual DbSet<Especialidad> Especialidad { get; set; }
        public virtual DbSet<ExperienciaRelacionada> ExperienciaRelacionada { get; set; }
        public virtual DbSet<NivelEducativo> NivelEducativo { get; set; }
        public virtual DbSet<NoDeCargos> NoDeCargos { get; set; }
        public virtual DbSet<OtraEspecialidad> OtraEspecialidad { get; set; }
        public virtual DbSet<PersonaDiligencia> PersonaDiligencia { get; set; }
        public virtual DbSet<PersonasReunionesPerfiles> PersonasReunionesPerfiles { get; set; }
        public virtual DbSet<JefeGesHum> JefeGesHum { get; set; }
        public virtual DbSet<EncuestaPerfilesPetroleo> EncuestaPerfilesPetroleo { get; set; }
        public virtual DbSet<PassEmpresas> PassEmpresas { get; set; }
    }
}
