//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienciaRelacionada
    {
        public ExperienciaRelacionada()
        {
            this.EncuestaPerfilesPetroleo = new HashSet<EncuestaPerfilesPetroleo>();
        }
    
        public int Id { get; set; }
        public string ExperienciaRelacionada1 { get; set; }
    
        public virtual ICollection<EncuestaPerfilesPetroleo> EncuestaPerfilesPetroleo { get; set; }
    }
}
