//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JefeGesHum
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Cargo { get; set; }
        public string CedulaCiudadania { get; set; }
        public int EmpresaId { get; set; }
        public string UserId { get; set; }
        public int Telefono { get; set; }
        public Nullable<long> Celular { get; set; }
        public string CorreoElectronioco { get; set; }
        public string Direccion { get; set; }
        public string Profesion { get; set; }
        public string Dependencia { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
