//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtraEspecialidad
    {
        public OtraEspecialidad()
        {
            this.Cargos = new HashSet<Cargos>();
            this.EmpresaEspecialidad = new HashSet<EmpresaEspecialidad>();
            this.PersonasReunionesPerfiles = new HashSet<PersonasReunionesPerfiles>();
            this.EncuestaPerfilesPetroleo = new HashSet<EncuestaPerfilesPetroleo>();
        }
    
        public int Id { get; set; }
        public string OtraEspecialidad1 { get; set; }
    
        public virtual ICollection<Cargos> Cargos { get; set; }
        public virtual ICollection<EmpresaEspecialidad> EmpresaEspecialidad { get; set; }
        public virtual ICollection<PersonasReunionesPerfiles> PersonasReunionesPerfiles { get; set; }
        public virtual ICollection<EncuestaPerfilesPetroleo> EncuestaPerfilesPetroleo { get; set; }
    }
}
