//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonasReunionesPerfiles
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Profesion { get; set; }
        public string CargoDependencia { get; set; }
        public string CorreoElectronico { get; set; }
        public string TelefonoCelular { get; set; }
        public int EmpresaId { get; set; }
        public int EspecialidadId { get; set; }
        public string UserId { get; set; }
    
        public virtual OtraEspecialidad OtraEspecialidad { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
